#!/bin/bash
#
# git-rank -- rank contributors for git
# Copyright (C) 2012  Alan SCHNEIDER
#                     <shk.schneider[at]gmail.com>
#
# This program comes with ABSOLUTELY NO WARRANTY.
# This is free software, and you are welcome to redistribute it
# under certain conditions.
#

[ -z "`which git`" ] && echo "git-rank: command 'git' not found" >&2 && exit 1

function usage() {
    echo "Usage: git-rank" >&2
    exit 1
}

dir=$(git rev-parse --git-dir 2>/dev/null)
[ -z "$dir" ] && echo "git-rank: not a git repository" >&2 && exit 1

[ $# -ne 0 ] && usage

rank="#"
rpl="@"

contributors=$(git log | egrep '^Author: ' | cut -d' ' -f2- | sed -r 's/ <.+>//g' | tr " " "$rpl" | sort | uniq)
for contributor in $contributors ; do
    real_contributor=$(echo $contributor | tr "$rpl" " ")
    n=$(git log | egrep  "^Author: $real_contributor <" | wc -l)
    rank=$(echo "$rank$n:$contributor#")
done

for contributor in $(echo $rank | tr "#" "\n" | sed -r "s/^$//g" | sort -rn) ; do
    n=$(echo $contributor | cut -d':' -f1)
    if [ $n -gt 0 ] ; then
	contributor=$(echo $contributor | cut -d':' -f2- | tr "$rpl" " ")
	contributor=$(git log | egrep "^Author: $contributor <" | head -1 | cut -d' ' -f2-)
	printf "%5d %s\n" "$n" "$contributor"
    fi
done

# EOF
