#!/bin/bash
#
# git-apply-url -- create a apply-url of a git repository/commit
# Copyright (C) 2012  Alan SCHNEIDER
#                     <shk.schneider[at]gmail.com>
# Copyright (C) 2008 Andrew Raines
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#

[ -z "`which git`" ] && echo "git-apply-url: command 'git' not found" >&2 && exit 1

function usage() {
    echo "Usage: git-apply-url <URL>" >&2
    exit 1
}

dir=$(git rev-parse --git-dir 2>/dev/null)
[ -z "$dir" ] && echo "git-apply-url: not a git repository" >&2 && exit 1

[ $# -ne 1 ] && usage

if [ -x "$(which curl)" ] && [ -n "$(curl -V | grep https)" ] ; then
    cmd="curl -s"
elif [ -x "$(which wget)" ] ; then
    cmd="wget -O - -q --no-check-certificate"
else
    echo "git-apply-url: could not found curl with https support nor wget" >&2 && exit 1
fi

$cmd "$1" | patch -p1

# EOF
