#!/bin/bash
#
# git-info -- shorter log
# Copyright (C) 2012  Alan SCHNEIDER
#                     <shk.schneider[at]gmail.com>
#
# This program comes with ABSOLUTELY NO WARRANTY.
# This is free software, and you are welcome to redistribute it
# under certain conditions.
#

[ -z "`which git`" ] && echo "git-info: command 'git' not found" >&2 && exit 1

function usage() {
    echo "Usage: git-info" >&2
    exit 1
}

dir=$(git rev-parse --git-dir 2>/dev/null)
[ -z "$dir" ] && echo "git-info: not a git repository" >&2 && exit 1

[ $# -ne 0 ] && usage

echo "== Repo"
repo=$(readlink -f $(dirname "$dir"))
echo "   $repo"
while read line ; do
    echo "   $line"
done < <(git remote -v | sed -n '1~2p' | awk '{print $2}')

echo "== Status"
branch=$(git branch --no-color | egrep '^\*' | cut -d' ' -f2)
echo -n "   branch $branch"
if [ $(git branch --no-color -a | grep -v HEAD | grep $branch | grep origin | wc -l) -gt 0 ] ; then
    echo " (public)"
else
    echo " (private)"
fi
commits=$(git status | sed -n '2p' | sed -r "s/'.+'//g" | sed -r 's/[^0-9]//g')
echo -n "   ahead by ${commits:=0} commits"
if [ $(git status --porcelain 2>/dev/null | wc -l) -gt 0 ] ; then
    echo " (dirty)"
else
    echo " (clean)"
fi

echo "== Branches"
while read line ; do
    line=$(echo "$line" | sed 's#^\*\s##g')
    echo "   $line"
done < <(git branch -a)

echo "== Latest commit"
commit=$(git log -n1 --oneline | cut -d' ' -f1)
author=$(git log -n 1 | egrep '^Author:' | cut -d' ' -f2- | sed -r 's/ <.+>$//')
msg=$(git log -n1 --oneline | cut -d' ' -f2-)
echo "   $commit [$author] $msg"

# EOF
